# Generated by Django 5.2.5 on 2026-03-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='descriptio',
            new_name='description',
        ),
    ]
