# Generated by Django 5.2.5 on 2026-04-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
